// Accelerator Configuration Package
// Generated by generate_config.py
// DO NOT EDIT DIRECTLY

package accelerator_config_pkg;

    // Data and Address Widths
    parameter DATA_WIDTH = 8;
    parameter ADDR_WIDTH = 16;
    
    // Tiling
    parameter TILE_ELEMS = 32;
    parameter TILE_WIDTH = 256; // TILE_ELEMS * DATA_WIDTH
    
    // Buffer Sizes
    parameter VECTOR_BUFFER_WIDTH = 8192;
    parameter MATRIX_BUFFER_WIDTH = 131072;
    
    // Architecture Limits
    parameter MAX_ROWS = 1024;
    parameter MAX_COLS = 1024;
    parameter OUT_N = 10;

endpackage
