import json
import os

# Default Configuration
DEFAULT_CONFIG = {
    "DATA_WIDTH": 8,
    "ADDR_WIDTH": 16,
    "TILE_ELEMS": 32,  # Number of elements in a tile (256 bits / 8 bits = 32)
    
    # Memory Size
    "MEM_SIZE": 0xF000,
    
    # Buffer Sizes (in bits, matching RTL parameters potentially, or bytes?)
    # RTL buffer_controller.sv uses BUFFER_WIDTH parameters.
    # VECTOR_BUFFER_WIDTH = 8192
    # MATRIX_BUFFER_WIDTH = 131072
    "VECTOR_BUFFER_WIDTH": 8192,
    "MATRIX_BUFFER_WIDTH": 131072,
    
    # Architecture Limits
    "MAX_ROWS": 1024,
    "MAX_COLS": 1024,
    "OUT_N": 10,
    
    # Memory Map (Offsets)
    "DRAM_ADDR_INPUTS": 0x00C0,
    "DRAM_ADDR_BIASES": 0x04C0,
    "DRAM_ADDR_OUTPUTS": 0x08C0,
    "DRAM_ADDR_WEIGHTS": 0x0940
}

def generate_rtl_package(config, output_path="rtl/accelerator_config_pkg.sv"):
    tile_width_bits = config["DATA_WIDTH"] * config["TILE_ELEMS"]
    
    content = f"""// Accelerator Configuration Package
// Generated by generate_config.py
// DO NOT EDIT DIRECTLY

package accelerator_config_pkg;

    // Data and Address Widths
    parameter DATA_WIDTH = {config["DATA_WIDTH"]};
    parameter ADDR_WIDTH = {config["ADDR_WIDTH"]};
    
    // Tiling
    parameter TILE_ELEMS = {config["TILE_ELEMS"]};
    parameter TILE_WIDTH = {tile_width_bits}; // TILE_ELEMS * DATA_WIDTH
    
    // Buffer Sizes
    parameter VECTOR_BUFFER_WIDTH = {config["VECTOR_BUFFER_WIDTH"]};
    parameter MATRIX_BUFFER_WIDTH = {config["MATRIX_BUFFER_WIDTH"]};
    
    // Architecture Limits
    parameter MAX_ROWS = {config["MAX_ROWS"]};
    parameter MAX_COLS = {config["MAX_COLS"]};
    parameter OUT_N = {config["OUT_N"]};

endpackage
"""
    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    with open(output_path, "w") as f:
        f.write(content)
    print(f"Generated {output_path}")

def generate_python_config(config, output_path="compiler/accelerator_config.py"):
    content = f"""# Accelerator Configuration Module
# Generated by generate_config.py
# DO NOT EDIT DIRECTLY

class AcceleratorConfig:
    DATA_WIDTH = {config["DATA_WIDTH"]}
    ADDR_WIDTH = {config["ADDR_WIDTH"]}
    
    TILE_ELEMS = {config["TILE_ELEMS"]}
    TILE_WIDTH = {config["DATA_WIDTH"] * config["TILE_ELEMS"]} 
    
    MEM_SIZE = {config["MEM_SIZE"]}
    
    VECTOR_BUFFER_WIDTH = {config["VECTOR_BUFFER_WIDTH"]}
    MATRIX_BUFFER_WIDTH = {config["MATRIX_BUFFER_WIDTH"]}
    
    MAX_ROWS = {config["MAX_ROWS"]}
    MAX_COLS = {config["MAX_COLS"]}
    OUT_N = {config["OUT_N"]}
    
    # Memory Map
    DRAM_ADDR_INPUTS = {config["DRAM_ADDR_INPUTS"]}
    DRAM_ADDR_BIASES = {config["DRAM_ADDR_BIASES"]}
    DRAM_ADDR_OUTPUTS = {config["DRAM_ADDR_OUTPUTS"]}
    DRAM_ADDR_WEIGHTS = {config["DRAM_ADDR_WEIGHTS"]}
"""
    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    with open(output_path, "w") as f:
        f.write(content)
    print(f"Generated {output_path}")

def main():
    config = DEFAULT_CONFIG
    
    # Check for memory_config.json overrides
    if os.path.exists("memory_config.json"):
        with open("memory_config.json", "r") as f:
            user_config = json.load(f)
            config.update(user_config)
            print("Loaded configuration from memory_config.json")
    
    generate_rtl_package(config)
    generate_python_config(config)

if __name__ == "__main__":
    main()
