# Accelerator Configuration Module
# Generated by generate_config.py
# DO NOT EDIT DIRECTLY

class AcceleratorConfig:
    DATA_WIDTH = 8
    ADDR_WIDTH = 16
    
    TILE_ELEMS = 32
    TILE_WIDTH = 256 
    
    MEM_SIZE = 61440
    
    VECTOR_BUFFER_WIDTH = 8192
    MATRIX_BUFFER_WIDTH = 131072
    
    MAX_ROWS = 1024
    MAX_COLS = 1024
    OUT_N = 10
    
    # Memory Map
    DRAM_ADDR_INPUTS = 192
    DRAM_ADDR_BIASES = 1216
    DRAM_ADDR_OUTPUTS = 2240
    DRAM_ADDR_WEIGHTS = 2368
